# fly.toml app configuration file generated for green-water-8044 on 2023-10-18T17:04:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-water-8044"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
